id: opecha:P000565
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG07866
  title: སྔ་འགྱུར་དགེ་མང་དགོན་གྱི་གདན་རབས་དང་མཁན་དོན་གྲུབ་ཉི་མ་མཆོག་གི་མཛད་རྣམ་མདོར་བསྡུས
  volume: ''
  author: ''
